# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master

pr:
  branches:
    include:
      - master

pool:
  name: 'Default'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.12'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install pre-commit
    displayName: 'Install pre-commit'

  - script: |
      pre-commit run --all-files
    displayName: 'Run pre-commit'

