services:
  frontend:
    environment:
      API_URL: http://api:8000
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "8501:8501"
    networks:
      - default_network

  backend:
    container_name: api
    environment:
      ALLOWED_HOSTS: "api,localhost"
      API_PORT: 8000
      SECRET_KEY: dev_secret
      DB_ADDRESS: database
      DB_USER: admin
      DB_PASSWORD: password
      DB_DATABASE: db
      DB_PORT: 5432
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    networks:
      - default_network
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default_network
    ports:
      - "5432:5432"

  migrations:
    environment:
      ALLOWED_HOSTS: "api,localhost"
      API_PORT: 8000
      SECRET_KEY: dev_secret
      DB_ADDRESS: database
      DB_USER: admin
      DB_PASSWORD: password
      DB_DATABASE: db
      DB_PORT: 5432
    build:
      context: ./backend
      dockerfile: ./migrations.Dockerfile
    ports:
      - "8000:8000"
    networks:
      - default_network
    depends_on:
      - db

networks:
  default_network:

volumes:
  db_data:
