apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: pjatksuml3scrummasterow.azurecr.io/kotkiipieski/frontend:latest
        ports:
        - containerPort: 8501
        env:
        - name: API_URL
          value: http://backend:8000
