apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keyvault-secrets
spec:
  provider: azure
  secretObjects:
    - secretName: backend-secrets
      type: Opaque
      data:
        - objectName: DB_ADDRESS
          key: postgresql-dbhost
        - objectName: DB_USER
          key: postgresql-admin
        - objectName: DB_PASSWORD
          key: postgresql-password
        - objectName: DB_DATABASE
          key: postgresql-dbname
        - objectName: DB_PORT
          key: postgresql-dbport

    - secretName: migration-secrets
      type: Opaque
      data:
        - objectName: DB_ADDRESS
          key: postgresql-dbhost
        - objectName: DB_USER
          key: postgresql-admin
        - objectName: DB_PASSWORD
          key: postgresql-password
        - objectName: DB_DATABASE
          key: postgresql-dbname
        - objectName: DB_PORT
          key: postgresql-dbport

    - secretName: db-secrets
      type: Opaque
      data:
        - objectName: DB_USER
          key: postgresql-admin
        - objectName: DB_PASSWORD
          key: postgresql-password

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    keyvaultName: "SUMLKeyVault"
    tenantId: "ae65f568-0ceb-42c2-9dda-731b9c16e6b4"
    objects: |
      array:
        - objectName: postgresql-admin
          objectType: secret
        - objectName: postgresql-dbhost
          objectType: secret
        - objectName: postgresql-dbname
          objectType: secret
        - objectName: postgresql-dbport
          objectType: secret
        - objectName: postgresql-password
          objectType: secret
    enableSecretRotation: "true"
