apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keyvault-secrets
spec:
  provider: azure
  secretObjects:
    - secretName: backend-secrets
      type: Opaque
      data:
        - objectName: postgresql-dbhost
          key: DB_ADDRESS
        - objectName: postgresql-admin
          key: DB_USER
        - objectName: postgresql-password
          key: DB_PASSWORD
        - objectName: postgresql-dbname
          key: DB_DATABASE
        - objectName: postgresql-dbport
          key: DB_PORT
        - objectName: django-secret
          key: SECRET_KEY
    - secretName: migration-secrets
      type: Opaque
      data:
        - objectName: postgresql-dbhost
          key: DB_ADDRESS
        - objectName: postgresql-admin
          key: DB_USER
        - objectName: postgresql-password
          key: DB_PASSWORD
        - objectName: postgresql-dbname
          key: DB_DATABASE
        - objectName: postgresql-dbport
          key: DB_PORT
        - objectName: django-secret
          key: SECRET_KEY
    - secretName: db-secrets
      type: Opaque
      data:
        - objectName: postgresql-admin
          key: DB_USER
        - objectName: postgresql-password
          key: DB_PASSWORD
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    keyvaultName: "SUMLKeyVault"
    userAssignedIdentityID: "9f4cf863-7fca-4beb-94cd-2888aff5120b"
    tenantId: "ae65f568-0ceb-42c2-9dda-731b9c16e6b4"
    objects: |
      array:
        - |
          objectName: postgresql-admin
          objectType: secret
        - |
          objectName: postgresql-dbhost
          objectType: secret
        - |
          objectName: postgresql-dbname
          objectType: secret
        - |
          objectName: postgresql-dbport
          objectType: secret
        - |
          objectName: postgresql-password
          objectType: secret
        - |
          objectName: django-secret
          objectType: secret
    enableSecretRotation: "true"
  syncSecret:
    enabled: true
