# Generated by Django 5.2 on 2025-05-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatDogPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.CharField(max_length=2000)),
                ('predicted_class', models.IntegerField()),
                ('prediction_date_time', models.DateTimeField()),
                ('is_vote_positive', models.BooleanField(blank=True, default=None, null=True)),
                ('feedback', models.CharField(blank=True, default=None, max_length=2000, null=True)),
                ('is_included_in_training_dataset', models.BooleanField(default=False)),
            ],
        ),
    ]
